services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  initdb:
    build: ./initdb
    depends_on:
      - redis
    entrypoint: ["sh", "-c", "sleep 2 && python init_data.py"]
    restart: "no"  # Runs only once

  redisinsight:
    image: redislabs/redisinsight:1.14.0
    container_name: redisinsight
    ports:
      - "8001:8001"
    volumes:
      - redisinsight_data:/db
    depends_on:
      - redis

volumes:
  redis-data:
  redisinsight_data:
